### ISSUE TITLE
Custom Prompts

### ISSUE THREAD

**Issue by AkbarShah96** [Mathux/TEMOS#16]
Hello, thanks for releasing the code for this awesome work! Does this repo currently support custom prompts? If not, could you highlight the necessary changes?

**Comment by Mathux** [comment]
Hi @AkbarShah96,

Disclaimer: if you are using in the wild custom prompts, it will probably fail to generate the desired motion. 

In fact, I have already created this script but did not commit the file. Since you asked and other people probably want to try, I just commit the necessary files: "interact.py" and "config/interact.yaml".

Then you can use this script as:

`python interact.py folder=outputs/kit-mmm-xyz/baseline/3l49g7hv/ saving=kick text="A person kicks with the right foot." length=60`

You can check the other arguments in "config/interact.yaml".

**Comment by AkbarShah96** [comment]
Thanks for providing this script!
