### ISSUE TITLE
About non-rescaled version

### ISSUE THREAD

**Issue by dwro0121** [Mathux/TEMOS#6]
Hello, I would like to use the non-scaled version suggested in your paper.

I'm reading the code and using it, but I wanna ask if it's right to do it the way below.

1. in `temos/model/metrics/compute.py`, 
https://github.com/Mathux/TEMOS/blob/d9d22064882b50a6a581afa44e878b2155cc4c7c/temos/model/metrics/compute.py#L26
I changed the parameter `force_in_meter` to `False`   
2. in `/temos/transforms/rots2joints/smplh.py`, 
https://github.com/Mathux/TEMOS/blob/d9d22064882b50a6a581afa44e878b2155cc4c7c/temos/transforms/rots2joints/smplh.py#L138-L140
I removed these codes when I use smpl data

Is this the correct way to proceed non-scaled version with smpl data?

Thanks!

**Comment by Mathux** [comment]
Hello,

The "non-scaled version" suggested in the paper corresponds to: 
- Joints regressed by a smpl layer, with the "mmm indexing" (which correspond roughly to MMM skeletons)
- Without the rescaling (multiplying by ``smplh_to_mmm_scaling_factor``). (with this option, it rescale the average SMPL body to MMM: it actually also convert from meters to millimeters). 
- With the change of axis (X Y Z => Y Z X), and with the right/left swap I did for MMM. I keep doing this, in order to use the same code for computing metrics (as the metric computation code depends on the axis order, and right/left swap does not matter [as it is the same transformation for GT]). 

1) Yes you are right about this, as by default I am doing rescaling to meter in the metrics for MMM. Without the rescaling, it is already in meters, so we need to disable this.

2) In theory you could remove this bloc of lines and it will work fine. But actually, you only need to choose ``jointstype=mmmns`` which means (mmm-non-scaled).  If you look at the code, it will not do the scaling:
https://github.com/Mathux/TEMOS/blob/d9d22064882b50a6a581afa44e878b2155cc4c7c/temos/transforms/rots2joints/smplh.py#L138
and it will still do the rest:
https://github.com/Mathux/TEMOS/blob/d9d22064882b50a6a581afa44e878b2155cc4c7c/temos/transforms/rots2joints/smplh.py#L144

**Comment by dwro0121** [comment]
Thank you for the reply.

**Comment by Mathux** [comment]
I saw your comment before you edited it, and in fact you are right. I updated the code accordingly to allow the usage of "mmmns" in ``rifke.py`` (so indirectly in the metric calculation).
https://github.com/Mathux/TEMOS/blob/f7841a61a9d29a3ba7055ed59ecc28329b261791/temos/transforms/joints2jfeats/rifke.py#L17

There might be some mistakes like that in the code, as I did not carefully re-tested this setting during the preparation of the code release. 

I may put more explanation in the ``README.md`` at some point.

Thanks for pointing this.

**Comment by dwro0121** [comment]
We also need to edit the below codes.

https://github.com/Mathux/TEMOS/blob/f7841a61a9d29a3ba7055ed59ecc28329b261791/temos/transforms/joints2jfeats/tools.py#L22

https://github.com/Mathux/TEMOS/blob/f7841a61a9d29a3ba7055ed59ecc28329b261791/temos/transforms/joints2jfeats/tools.py#L30

**Comment by Mathux** [comment]
Yes true, I just did it thanks 👍
